#!/bin/bash

ln -s -f $HOME/.dotfiles/zsh/.zshrc $HOME
ln -s -f $HOME/.dotfiles/zsh/.zshenv $HOME
ln -s -f $HOME/.dotfiles/git/.gitconfig $HOME
ln -s -f $HOME/.dotfiles/vim/.vimrc $HOME
ln -s -f $HOME/.dotfiles/tmux/gpakosz_tmux/.tmux.conf $HOME
ln -s -f $HOME/.dotfiles/tmux/.tmux.conf.local $HOME
ln -s -f $HOME/.dotfiles/npm/.npmrc $HOME
