tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
cask "xquartz"
brew "bash-completion"
brew "carthage"
brew "cdrtools"
brew "cloc"
brew "cmake"
brew "curl", args: ["with-openssl"], link: true
brew "diff-so-fancy"
brew "entr"
brew "ffmpeg"
brew "git"
brew "hicolor-icon-theme"
brew "git-annex"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "gmp"
brew "libtool"
brew "graphicsmagick"
brew "gsl"
brew "pangomm"
brew "gtkmm"
brew "highlight"
brew "htop"
brew "imagemagick"
brew "imapsync"
brew "libdvdcss", link: false
brew "little-cms2"
brew "mas"
brew "netcat"
brew "pipenv"
brew "pyenv"
brew "reattach-to-user-namespace"
brew "stubby", restart_service: true
brew "swaks"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tmux"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "adium"
cask "adobe-creative-cloud"
cask "adobe-digital-editions"
cask "airserver"
cask "alfred"
cask "anaconda"
cask "angry-ip-scanner"
cask "appcleaner"
cask "arduino"
cask "bitbar"
cask "calibre"
cask "cyberduck"
cask "dash"
cask "deluge"
cask "divvy"
cask "docker"
cask "dropbox"
cask "figma"
cask "fiji"
cask "firefox"
cask "gephi"
cask "google-backup-and-sync"
cask "google-chrome"
cask "handbrake"
cask "insomnia"
cask "interface-inspector"
cask "iterm2"
cask "mactex"
cask "marble"
cask "monodraw"
cask "ngrok"
cask "pdf-expert"
cask "remarkable"
cask "rocket"
cask "sourcetree"
cask "spotify"
cask "sublime-text"
cask "teamviewer"
cask "thebrain"
cask "torbrowser"
cask "transmission"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "vlc"
cask "wine-stable"
mas "BetterSnapTool", id: 417375580
mas "Clear", id: 504544917
mas "Condense", id: 715394237
mas "DaisyDisk", id: 411643860
mas "EFQRCode", id: 1306793539
mas "Fantastical 2", id: 975937182
mas "GIF Brewery 3", id: 1081413713
mas "Helium", id: 1054607607
mas "LittleIpsum", id: 405772121
mas "Paste", id: 967805235
mas "QuickSketch", id: 1079970088
mas "Shazam", id: 897118787
mas "Sip", id: 507257563
mas "The Unarchiver", id: 425424353
mas "Trello", id: 1278508951
mas "Unclutter", id: 577085396
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
