# tap (sources of formulae)
tap "buo/cask-upgrade" # interactive brew cask upgrade
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# brew (binaries)
brew "awscli"
brew "bash-completion"
brew "brotli"
brew "bundletool"
brew "cloc"
brew "cmake"
brew "diff-so-fancy"
brew "ffmpeg"
brew "git"
brew "hicolor-icon-theme"
brew "git-annex"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "libtool"
brew "htop"
brew "jq"
brew "libdvdcss"
brew "libxml2"
brew "mas"
brew "netcat"
brew "nvm"
brew "nginx"
brew "p7zip"
brew "pipenv"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "wget"
brew "wireguard-tools"
brew "youtube-dl"
brew "zsh"
brew "gh"

# casks (programs/large binaries)
cask "1password-cli"
cask "alfred"
cask "cryptomator"
cask "dash"
cask "divvy"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "iterm2"
cask "ngrok"
cask "sip"
cask "spark"
cask "sublime-merge"
cask "visual-studio-code"

# mas (App Store)
mas "Paste - Clipboard Manager", id: 967805235
mas "Yoink - Improved Drag and Drop", id: 457622435
mas "Spark – Email App by Readdle", id: 1176895641
mas "Microsoft OneNote", id: 784801555